version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3000:3000
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    network_mode: service:mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
  web:
    build:
      dockerfile: Dockerfile
      context: "./client"
    network_mode: service:mongo
    volumes:
      - ./client:/app
    command: bash -c "sleep 10; npm run start"
  server:
    build:
      dockerfile: Dockerfile
      context: "./graphqlServer"
    network_mode: service:mongo
    volumes:
      - ./graphqlServer:/app
    command: bash -c "sleep 10; npm run start-local"
