export const USER_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOG_OUT: "LOG_OUT",
}
export const SCHOOL_ACTIONS = {
  AUTHENTICATE_REQUEST: 'AUTHENTICATE_REQUEST',
  AUTHENTICATE_SUCCESS: 'AUTHENTICATE_SUCCESS',
  // school actions
  GET_SCHOOLS_REQUEST: 'GET_SCHOOLS_REQUEST',
  GET_SCHOOLS_SUCCESS: 'GET_SCHOOLS_SUCCESS',
  CREATE_SCHOOL_REQUEST: 'CREATE_SCHOOL_REQUEST',
  CREATE_SCHOOL_SUCCESS: 'CREATE_SCHOOL_SUCCESS',
  JOIN_SCHOOL_REQUEST: 'JOIN_SCHOOL_REQUEST',
  JOIN_SCHOOL_SUCCESS: 'JOIN_SCHOOL_SUCCESS',
  // class actions
  UPDATE_CLASS_REQUEST: 'UPDATE_CLASS_REQUEST',
  UPDATE_CLASS_SUCCESS: 'UPDATE_CLASS_SUCCESS',
  ADD_CLASS_REQUEST: 'ADD_CLASS_REQUEST',
  ADD_CLASS_SUCCESS: 'ADD_CLASS_SUCCESS',
  DELETE_CLASS_REQUEST: 'DELETE_CLASS_REQUEST',
  DELETE_CLASS_SUCCESS: 'DELETE_CLASS_SUCCESS',
  // teacher actions
  ADD_TEACHER_REQUEST: 'ADD_TEACHER_REQUEST',
  ADD_TEACHER_SUCCESS: 'ADD_TEACHER_SUCCESS',
  UPDATE_TEACHER_REQUEST: 'UPDATE_TEACHER_REQUEST',
  UPDATE_TEACHER_SUCCESS: 'UPDATE_TEACHER_SUCCESS',
  DELETE_TEACHER_REQUEST: 'DELETE_TEACHER_REQUEST',
  DELETE_TEACHER_SUCCESS: 'DELETE_TEACHER_SUCCESS',
  // student actions
  ADD_STUDENT_REQUEST: 'ADD_STUDENT_REQUEST',
  ADD_STUDENT_SUCCESS: 'ADD_STUDENT_SUCCESS',
  UPDATE_STUDENT_REQUEST: 'UPDATE_STUDENT_REQUEST',
  UPDATE_STUDENT_SUCCESS: 'UPDATE_STUDENT_SUCCESS',
  DELETE_STUDENT_REQUEST: 'DELETE_STUDENT_REQUEST',
  DELETE_STUDENT_SUCCESS: 'DELETE_STUDENT_SUCCESS',
  //
  UPLOAD_CLASS_REQUEST: 'UPLOAD_CLASS_REQUEST',
  UPLOAD_CLASS_SUCCESS: 'UPLOAD_CLASS_SUCCESS',
}

export const LANGUAGES = {
  ENGLISH: "en",
}

export const ID_TYPE = {
  CLASS_ID: 'classId',
  TEACHER_ID: 'teacherId',
  SCHOOL_ID: 'schoolId',
}
