export const USER_ACTIONS = {
  LOGIN: "LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOG_OUT: "LOG_OUT",
  LOGIN_ERROR: "LOGIN_ERROR",
  SIGN_UP: "SIGN_UP",
  SIGN_UP_ERROR: "SIGN_UP_ERROR"
}
export const SCHOOL_ACTIONS = {
  ADD_STUDENT_REQUEST: 'ADD_STUDENT_REQUEST',
  ADD_STUDENT: 'ADD_STUDENT',
  ADD_TEACHER_REQUEST: 'ADD_TEACHER_REQUEST',
  ADD_TEACHER: 'ADD_TEACHER',
  UPDATE_TEACHER_REQUEST: 'UPDATE_TEACHER_REQUEST',
  UPDATE_TEACHER: 'UPDATE_TEACHER',
  UPDATE_CLASS_REQUEST: 'UPDATE_CLASS_REQUEST',
  UPDATE_CLASS: 'UPDATE_CLASS',
  ADD_CLASS_REQUEST: 'ADD_CLASS_REQUEST',
  ADD_CLASS: 'ADD_CLASS',
  ADD_STUDENT_REQUEST: 'ADD_STUDENT_REQUEST',
  ADD_STUDENT: 'ADD_STUDENT',
  UPDATE_STUDENT_REQUEST: 'UPDATE_STUDENT_REQUEST',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  UPLOAD_CLASS_REQUEST: 'UPLOAD_CLASS_REQUEST',
  UPLOAD_CLASS: 'UPLOAD_CLASS'
}
